name: request

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: https request
        shell: bash
        run: |
          curl -X GET https://exhibition-here.herokuapp.com/pages
