name: request

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: http request
        shell: bash
        run: curl -X GET https://exhibition-here.herokuapp.com/pages