name: DBUpdate

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: checkout backend
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: gradlew authorization
        run: chmod +x ./gradlew

      - name: build gradle
        run: ./gradlew build

      - name: run gradle
        run: ./gradlew bootRun